# Generated by Django 6.0.2 on 2026-02-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('GLOBAL', 'All Users'), ('ADMIN', 'Admins'), ('HEAD', 'Headteachers'), ('TEACHER', 'Teachers'), ('STUDENT', 'Students'), ('PARENT', 'Parents'), ('ACCOUNTANT', 'Accountants'), ('CLASS', 'Specific Class')], default='GLOBAL', max_length=10)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.class')),
            ],
            options={
                'permissions': [('can_create_announcement', 'Can create announcements')],
            },
        ),
    ]
