# Generated by Django 6.0.2 on 2026-02-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('MONEY', 'Money / Fees (Accountant)'), ('STUDY', 'Study / Academics (DOS)'), ('DISCIPLINE', 'Discipline / Behavior (DOD)'), ('GENERAL', 'Public / General (Headteacher)')], default='GENERAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
