# Generated by Django 6.0.2 on 2026-02-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('action_taken', models.CharField(help_text='Action taken by DOS or Headteacher', max_length=200)),
                ('managed_by', models.ForeignKey(limit_choices_to={'profile__role': 'DOS'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_discipline_cases', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_discipline_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='Academics.student')),
            ],
            options={
                'verbose_name_plural': 'Discipline Records',
            },
        ),
        migrations.CreateModel(
            name='OperationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='approvals/')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('headteacher', models.ForeignKey(limit_choices_to={'profile__role': 'HEAD'}, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_operations', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dos', models.ForeignKey(limit_choices_to={'profile__role': 'DOS'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
