# Generated by Django 6.0.3 on 2026-05-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='room',
            field=models.CharField(blank=True, help_text='Room number or location', max_length=50),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicterm'),
        ),
    ]
