# Generated by Django 6.0.3 on 2026-05-29 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_enrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date'], 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submission_date'], 'verbose_name_plural': 'Assignment Submissions'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
