# Generated by Django 6.0.2 on 2026-02-21 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Annual Tuition Fee, Term 1 Library Fee', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_required', models.BooleanField(default=True, help_text='Is this fee mandatory for all students?')),
                ('academic_period', models.CharField(default='2024/2025 - Term 1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('fee_details', models.TextField(help_text='JSON representation of fee components.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Credit/Debit Card')], max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for bank/external payment reference.', unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.invoice')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'profile__role': 'ACCOUNTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
