# Generated by Django 6.0.2 on 2026-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
