# Generated by Django 6.0.3 on 2026-05-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_classschedule_is_active_classschedule_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Reunion', 'Reunion'), ('Networking', 'Networking'), ('Career Fair', 'Career Fair'), ('Fundraising', 'Fundraising'), ('Speaker Series', 'Speaker Series'), ('Other', 'Other')], default='Networking', max_length=50)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni Events',
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('graduation_class', models.CharField(max_length=100)),
                ('current_occupation', models.CharField(blank=True, max_length=200)),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_willing_to_mentor', models.BooleanField(default=False)),
                ('is_willing_to_speak', models.BooleanField(default=False)),
                ('is_willing_to_donate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alumni Profiles',
            },
        ),
        migrations.CreateModel(
            name='AlumniJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Remote', 'Remote')], default='Full-time', max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('application_link', models.URLField(blank=True)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='alumni.alumniprofile')),
            ],
            options={
                'verbose_name_plural': 'Alumni Job Postings',
            },
        ),
        migrations.CreateModel(
            name='AlumniDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_purpose', models.CharField(blank=True, max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='alumni.alumniprofile')),
            ],
            options={
                'verbose_name_plural': 'Alumni Donations',
            },
        ),
        migrations.CreateModel(
            name='AlumniMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('mentorship_area', models.CharField(help_text='e.g., Career guidance, Academic support', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='academics.student')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='alumni.alumniprofile')),
            ],
            options={
                'verbose_name_plural': 'Alumni Mentorships',
                'unique_together': {('mentor', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AlumniEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='alumni.alumnievent')),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='alumni.alumniprofile')),
            ],
            options={
                'verbose_name_plural': 'Alumni Event Registrations',
                'unique_together': {('event', 'alumni')},
            },
        ),
    ]
