# Generated by Django 6.0.2 on 2026-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_user_id_profile_user_profile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('HEAD', 'Headmaster'), ('ACCOUNTANT', 'Accountant'), ('DOS', 'Dean of Study'), ('DOD', 'Director of Discipline')], default='STUDENT', max_length=15),
        ),
    ]
