# Generated by Django 6.0.2 on 2026-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('HEAD', 'Headmaster'), ('ACCOUNTANT', 'Accountant'), ('DOS', 'Dean of Study'), ('DOD', 'Director of Discipline'), ('ANIMATEUR', 'Animateur'), ('ANIMATRICE', 'Animatrice'), ('POPULAR', 'Popular Staff')], default='STUDENT', max_length=15),
        ),
    ]
