# Generated by Django 6.0.3 on 2026-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_teacher', 'Head Teacher'), ('dos', 'Director of Studies (DOS)'), ('dod', 'Director of Discipline (DOD)'), ('teacher', 'Teacher'), ('animateur', 'Animateur'), ('animatrice', 'Animatrice'), ('accountant', 'Accountant'), ('student', 'Student'), ('parent', 'Parent'), ('public', 'Public / Visitor')], default='public', max_length=20),
        ),
    ]
