# Generated by Django 6.0.3 on 2026-05-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classschedule_is_active_classschedule_room_and_more'),
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('relationship_to_student', models.CharField(default='Parent/Guardian', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_guardian', models.BooleanField(default=False)),
                ('can_view_grades', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_view_discipline', models.BooleanField(default=True)),
                ('can_view_fees', models.BooleanField(default=True)),
                ('relationship_type', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Step-parent', 'Step-parent'), ('Other', 'Other')], default='Guardian', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='academics.student')),
            ],
            options={
                'verbose_name_plural': 'Parent-Student Relationships',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
