# Generated by Django 6.0.3 on 2026-03-23 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                ('default_action', models.CharField(blank=True, max_length=200)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Discipline Categories',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='discipline_evidence/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('appealed', 'Under Appeal'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'dod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_cases', to='academics.student')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discipline.disciplinecategory')),
            ],
            options={
                'ordering': ['-reported_date'],
                'permissions': [('can_investigate_case', 'Can investigate discipline cases'), ('can_resolve_case', 'Can resolve discipline cases'), ('can_appeal_case', 'Can appeal discipline cases')],
            },
        ),
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('community_service', 'Community Service'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('counseling', 'Counseling Session'), ('parent_meeting', 'Parent Meeting'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='discipline.disciplinecase')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('parent_present', models.BooleanField(default=False)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_comment', models.TextField(blank=True)),
                ('student_statement', models.TextField(blank=True)),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('decision', models.TextField()),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('is_appealed', models.BooleanField(default=False)),
                ('appeal_reason', models.TextField(blank=True)),
                ('appeal_decision', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hearing', to='discipline.disciplinecase')),
                ('chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_hearings', to=settings.AUTH_USER_MODEL)),
                ('committee_members', models.ManyToManyField(related_name='hearing_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_date', models.DateField()),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases_included', models.ManyToManyField(blank=True, to='discipline.disciplinecase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('major_cases', models.IntegerField(default=0)),
                ('minor_cases', models.IntegerField(default=0)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
                ('is_on_probation', models.BooleanField(default=False)),
                ('probation_end_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicyear')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_record', to='academics.student')),
            ],
            options={
                'ordering': ['-academic_year', 'student'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
